name = "docbuild"
reservoir = false
version = "0.1.0"
packagesDir = "../.lake/packages"

[[require]]
name = "pdl"
path = ".."

[[require]]
name = "doc-gen4"
git = "https://github.com/m4lvin/doc-gen4"
rev = "show-sorryAx"
