-- adapted from https://leanprover.zulipchat.com/#narrow/channel/113488-general/topic/Finding.20useless.20code.20in.20a.20project/near/596066478

import Lean
import Pdl

open Lean

def nameCode (n : Name) : String :=
  if n = .anonymous then
    "anonymous"
  else
    n.toString.replace "." "_"

def nameDisplay (n : Name) : String :=
  n.components.getLast!.toString

def printDeps₁ (k : Name) (_v : Array Name) (print : String → IO Unit) : IO Unit := do
  let n := k.componentsRev[1]!
  print (nameCode k ++ " [label=\"" ++ nameDisplay k ++ "\"" ++
    " group=\"" ++ n.toString ++ "\"]" ++ ";\n")

def printDeps₂ (k : Name) (v : Array Name) (print : String → IO Unit) : IO Unit := do
  for val in v do
    if (`Pdl).isPrefixOf val then
      print (nameCode val ++ " -> " ++ nameCode k ++ ";\n")

def group (name : Name) : Name :=
  (name.eraseSuffix? name.componentsRev.head!).get!

def groups (imports : NameMap (Array Name)) : NameMap Unit :=
  imports.foldl (fun xs k _ =>
    if (`Pdl).isPrefixOf k then xs.insert (group k) () else xs) ∅

/-- `#deptree` outputs a graphviz dependency graph to `depgraph.dot`. Build it with
`dot -Tpdf -Gnewrank=true -Goverlaps=false -Gsplines=ortho depgraph.dot > depgraph.pdf`. -/
elab "#deptree " : command => do
  let env ← getEnv
  let imports := env.importGraph
  IO.FS.withFile "docs/depgraph.dot" IO.FS.Mode.write fun h => do
  h.write "digraph {\n".toUTF8
  h.write "compound=true;\n".toUTF8
  for (gp, _) in groups imports do
    h.write ("subgraph cluster_" ++ nameCode gp ++ " {\n").toUTF8
    for (k, v) in imports do
      if (`Pdl).isPrefixOf k && group k = gp then do
        printDeps₁ k v (fun s => h.write s.toUTF8)
    h.write ("label = \"" ++ gp.toString ++ "\";\n").toUTF8
    h.write ("margin = 32;\n").toUTF8
    h.write ("pad = 32;\n").toUTF8
    h.write ("penwidth = 5;\n").toUTF8
    h.write ("color = cyan4;\n").toUTF8
    h.write "}\n".toUTF8
  for (k, v) in imports do
    if (`Pdl).isPrefixOf k then do
      printDeps₂ k v (fun s => h.write s.toUTF8)
  h.write "}\n".toUTF8

/-- Name components that Lean uses for declarations it generates automatically,
for example `Foo.bar.eq_def`, `Foo.ctorIdx` or `Foo.brecOn.eq`. -/
def autoGenParts : List String :=
  [ "eq_def", "injEq", "sizeOf_spec", "ctorIdx", "toCtorIdx", "congr_simp", "hinj",
    "noConfusion", "noConfusionType", "brecOn", "below", "ibelow", "binductionOn",
    "rec", "recOn", "casesOn" ]

/-- Like `autoGenParts`, but with a number attached, for example `match_1`,
`congr_eq_4`, `hcongr_5` or `repr_2`. -/
def autoGenNumberedParts : List String :=
  [ "match_", "congr_eq_", "hcongr_", "proof_", "repr_", "eq_", "below_", "brecOn_",
    "binductionOn_" ]

/-- Is this one of the `autoGenParts` or `autoGenNumberedParts`? -/
def isAutoGenPart (s : String) : Bool :=
  autoGenParts.contains s ||
    autoGenNumberedParts.any fun p =>
      s.startsWith p && p.length < s.length && (s.drop p.length).all Char.isDigit

/-- Is `n` the name of a notation, i.e. of something declared with `notation`,
`syntax`, `macro` etc.? Such declarations are of type `Lean.ParserDescr`. -/
def isNotation (env : Environment) (n : Name) : Bool :=
  match env.find? n with
  | some ci => ci.type.isConstOf ``Lean.ParserDescr || ci.type.isConstOf ``Lean.TrailingParserDescr
  | none => false

/-- Was `n` generated automatically, e.g. by `deriving`, by the equation compiler
or by a `notation` command? Such declarations are not interesting for `#unseen`. -/
def isAutoGenerated (env : Environment) (n : Name) : Bool :=
  Lean.isReservedName env n || n.components.any (isAutoGenPart <| toString ·) || isNotation env n

partial def allDeclsIn (module : Name) : Elab.Command.CommandElabM (Array Name) := do
  let env ← getEnv
  let mFile ← findOLean module
  unless (← mFile.pathExists) do
    logError m!"object file '{mFile}' of module {module} does not exist"
  let (md, _) ← readModuleData mFile
  let decls ← md.constNames.filterM fun d =>
    return !(← d.isBlackListed) && !isAutoGenerated env d
  return decls

def allFiles (env : Environment) : List Name :=
  (env.importGraph.foldl (fun xs k _ => if (`Pdl).isPrefixOf k then
    k :: xs else xs) []).mergeSort
    (toString · < toString ·)

def allDecls (env : Environment) : Elab.Command.CommandElabM NameSet :=
  (fun l => NameSet.ofList (l.map (fun a => a.toList)).flatten) <$>
    (List.mapM allDeclsIn (allFiles env))

/-- `#index` computes an index of the declations in the project and saves it to `index.csv`. -/
elab "#index " : command => do
  let env ← getEnv
  let allDecls ← allDecls env
  let result ← List.mapM (fun decl => do
    let ranges ← findDeclarationRanges? decl
    let mod ← findModuleOf? decl
    match (ranges, mod) with
    | (some ranges, some mod) => pure (some (decl, ranges, mod))
    | _ => pure none)
    (allDecls.toList.mergeSort (toString · < toString ·))
  let result' := result.filterMap id
  IO.FS.withFile "docs/index.csv" IO.FS.Mode.write (fun h => do
    for (decl, ranges, mod) in result' do
      h.write (decl.toString ++ ", " ++ mod.toString ++ ", " ++
        ranges.range.pos.line.repr ++ ", " ++ ranges.range.pos.column.repr ++ "\n").toUTF8)

/-- `#unseen` computes a list of the declarations in the project that are
defined but not used. The list is stored in `unseen_defs.txt`. -/
elab "#unseen " : command => do
  let env ← getEnv
  let allDecls ← allDecls env
  let timeStart ← IO.monoMsNow
  let unseen := env.constants.fold (init := allDecls) fun unseen name info =>
    info.getUsedConstantsAsSet.foldl (init := unseen) fun unseen x =>
      if x = name then unseen else unseen.erase x
  IO.FS.withFile "scripts/unseen_defs.txt" IO.FS.Mode.write (fun h => do
    for v in unseen.toList.mergeSort (toString · < toString ·) do
      h.write (v.toString ++ "\n").toUTF8)
  let timeEnd ← IO.monoMsNow
  logInfo m!"operation took {(timeEnd - timeStart) / 1000}s"

-- #unseen
